# Setup
title:            Ben Mitchell
tagline:          'Welcome to my site!'
description:      'Computer Science @ the <a href="https://leeds.ac.uk" target="_blank">University of Leeds</a>'
url:              'http://localhost:4000'
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Ben Mitchell'
  url:            https://twitter.com/benjomit

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# GitHub
github:
  user:           https://github.com/CRISPYricePC
  repo:           https://github.com/CRISPYricePC/hyde

# GitLab
gitlab:
  user:           https://gitlab.com/CRISPYrice

# Custom vars
version:          3.0.0

# CSS
sass:
  sass_dir:     ./_scss